default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: open_index_development

test:
  <<: *default
  database: open_index_test

production:
  <<: *default
  database: open_index_production
  username: myapp
  password: <%= ENV['OPEN_INDEX_DATABASE_PASSWORD'] %>
